### ISSUE TITLE
Make policies upgradeable

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/claims-manager#28]
Coverage amount and expiry of policies should be upgradeable

**Comment by bbenligiray** [comment]
@ErichDylus This requires these details to not be in the IPFS doc

**Comment by ErichDylus** [comment]
This is referring to a given service coverage purchaser's policy document, correct? (i.e. [this](https://github.com/ErichDylus/API3/blob/main/forms/Service%20Coverage%20Policy%20Template.md))

Should we consider pushing each entire policy doc on-chain as a hash of the text, or mapped hash, that way it could be novated as a whole rather than separating between the on-chain upgradeable params and the IPFS doc? Or what did you have in mind

**Comment by bbenligiray** [comment]
> This is referring to a given service coverage purchaser's policy document, correct?

Yes

So the idea is that we should be able to update total policy coverage and expiration date upon additional payment. It doesn't work if the IPFS hash is a part of the policy hash and the IPFS doc includes the old coverage and expiration date. The policy coverage and the expiration date is already stored on-chain as a part of the policy hash, so these being in the IPFS doc is redundant in the first place. So it feels like just removing these fields from the policy document should suffice.

This policy upgrade story is very new so I'm not sure if it's actually necessary and this is how it should be implemented, I just wanted to document asap.
