### ISSUE TITLE
Add metadata into the policy hash

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/claims-manager#30]
and add that as argument to claim creation

**Comment by bbenligiray** [comment]
@mcoetzee Can you remind me why we needed this?

**Comment by mcoetzee** [comment]
This was mostly about simplifying things for the frontend. We want to use the policy metadata as the text of the link to the associated policy (on the My Claims page), and we currently pass in all policy fields when creating a claim, so this issue was about also passing in the metadata, and including it in the `CreatedClaim` event.
<img width="653" alt="Screenshot 2022-08-15 at 09 21 13" src="https://user-images.githubusercontent.com/747979/184592989-d38273d6-2219-42a0-96d2-69ef8985b790.png">

**Comment by bbenligiray** [comment]
Thanks, I remember now
