### ISSUE TITLE
"Invalid claim index" exception thrown for first dispute

### ISSUE THREAD

**Issue by mcoetzee** [api3dao/claims-manager#43]
This is a similar issue to https://github.com/api3dao/claims-manager/issues/23, i.e. `KlerosLiquidProxy#onlyDisputedClaim()` throws an exception for the very first dispute, because the first dispute's id is zero:
```solidity
// KlerosLiquidProxy.sol

    modifier onlyDisputedClaim(uint256 claimIndex) {
        require(claimIndexToDisputeId[claimIndex] != 0, "Invalid claim index");
        _;
    }
```

This time I don't have an easy fix, as the dispute id gets assigned by the arbitrator contract.

**Comment by bbenligiray** [comment]
This is something I wanted to ask you about, I implemented the `KlerosLiquidProxy` interface to work with claim indices instead of dispute IDs, but I'm not sure if this is needed. You can just fetch the `CreatedDispute` logs to create the claim index -> dispute ID mapping and use the dispute IDs, then I wouldn't need to keep `claimIndexToDisputeId` or use `onlyDisputedClaim()`.

**Comment by mcoetzee** [comment]
Yes the frontend does have the dispute ID handy (it fetches the `CreatedDispute` logs).
